import PDFDocument from "pdfkit";

import type { InvoiceDetail, InvoiceIssuer, InvoicePdfRenderer } from "./types.js";

const colors = {
  ink: "#172033",
  muted: "#667085",
  line: "#D9E0EA",
  panel: "#F4F7FB",
  brand: "#2447D8",
  success: "#157A55",
  warning: "#A55B08"
};

const margin = 48;
const tableColumns = {
  description: { x: 48, width: 250 },
  quantity: { x: 306, width: 58 },
  unitPrice: { x: 372, width: 78 },
  lineTotal: { x: 458, width: 89 }
};

function formatDate(value: string): string {
  return new Intl.DateTimeFormat("en-GB", {
    day: "2-digit",
    month: "short",
    year: "numeric",
    timeZone: "UTC"
  }).format(new Date(`${value}T00:00:00.000Z`));
}

function formatMoney(value: string, currency: string): string {
  const [integer, decimal = "00"] = value.split(".");
  const grouped = integer!.replace(/\B(?=(\d{3})+(?!\d))/g, ",");
  return `${currency} ${grouped}.${decimal.padEnd(2, "0").slice(0, 2)}`;
}

function statusColor(status: InvoiceDetail["status"]): string {
  if (status === "PAID") return colors.success;
  if (status === "OVERDUE") return colors.warning;
  return colors.brand;
}

function drawTableHeader(document: PDFKit.PDFDocument, y: number): number {
  document.rect(margin, y, 499, 26).fill(colors.ink);
  document
    .fillColor("#FFFFFF")
    .font("Helvetica-Bold")
    .fontSize(8)
    .text("DESCRIPTION", tableColumns.description.x + 8, y + 9, {
      width: tableColumns.description.width - 16
    })
    .text("QTY", tableColumns.quantity.x, y + 9, {
      width: tableColumns.quantity.width,
      align: "right"
    })
    .text("UNIT PRICE", tableColumns.unitPrice.x, y + 9, {
      width: tableColumns.unitPrice.width,
      align: "right"
    })
    .text("AMOUNT", tableColumns.lineTotal.x, y + 9, {
      width: tableColumns.lineTotal.width - 8,
      align: "right"
    });
  return y + 26;
}

function ensureTableSpace(document: PDFKit.PDFDocument, y: number, height: number): number {
  if (y + height <= document.page.height - 92) return y;
  document.addPage();
  return drawTableHeader(document, margin);
}

function drawFooter(document: PDFKit.PDFDocument): void {
  const range = document.bufferedPageRange();
  for (let index = range.start; index < range.start + range.count; index += 1) {
    document.switchToPage(index);
    const y = document.page.height - 48;
    const previousBottomMargin = document.page.margins.bottom;
    document.page.margins.bottom = 0;
    document.moveTo(margin, y - 10).lineTo(document.page.width - margin, y - 10).strokeColor(colors.line).stroke();
    document
      .fillColor(colors.muted)
      .font("Helvetica")
      .fontSize(8)
      .text("Generated by InvoicePro", margin, y, { lineBreak: false });
    document.text(
      `Page ${index - range.start + 1} of ${range.count}`,
      document.page.width - margin - 100,
      y,
      {
        align: "right",
        width: 100,
        lineBreak: false
      }
    );
    document.page.margins.bottom = previousBottomMargin;
  }
}

export class PdfKitInvoiceRenderer implements InvoicePdfRenderer {
  constructor(private readonly issuer: InvoiceIssuer) {}

  async render(invoice: InvoiceDetail): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const document = new PDFDocument({
        size: "A4",
        margin,
        bufferPages: true,
        info: {
          Title: `Invoice ${invoice.invoiceNumber}`,
          Author: this.issuer.name,
          Subject: `Invoice for ${invoice.client.businessName}`
        }
      });
      const chunks: Buffer[] = [];
      document.on("data", (chunk: Buffer) => chunks.push(chunk));
      document.on("error", reject);
      document.on("end", () => resolve(Buffer.concat(chunks)));

      document.rect(0, 0, document.page.width, 120).fill(colors.ink);
      document
        .fillColor("#FFFFFF")
        .font("Helvetica-Bold")
        .fontSize(18)
        .text(this.issuer.name, margin, 36, { width: 300 });
      document
        .font("Helvetica-Bold")
        .fontSize(30)
        .text("INVOICE", document.page.width - margin - 180, 32, {
          width: 180,
          align: "right"
        });
      document
        .fillColor("#D9E2FF")
        .font("Helvetica")
        .fontSize(9)
        .text([this.issuer.address, this.issuer.email].filter(Boolean).join(" | "), margin, 68, {
          width: document.page.width - margin * 2
        });

      const metadataY = 148;
      document.fillColor(colors.muted).font("Helvetica-Bold").fontSize(8).text("INVOICE NUMBER", margin, metadataY);
      document.fillColor(colors.ink).font("Helvetica-Bold").fontSize(12).text(invoice.invoiceNumber, margin, metadataY + 14);
      document.fillColor(colors.muted).font("Helvetica-Bold").fontSize(8).text("ISSUE DATE", 255, metadataY);
      document.fillColor(colors.ink).font("Helvetica").fontSize(10).text(formatDate(invoice.issueDate), 255, metadataY + 14);
      document.fillColor(colors.muted).font("Helvetica-Bold").fontSize(8).text("DUE DATE", 365, metadataY);
      document.fillColor(colors.ink).font("Helvetica").fontSize(10).text(formatDate(invoice.dueDate), 365, metadataY + 14);
      document
        .roundedRect(471, metadataY - 2, 76, 32, 5)
        .fill(statusColor(invoice.status));
      document
        .fillColor("#FFFFFF")
        .font("Helvetica-Bold")
        .fontSize(9)
        .text(invoice.status, 471, metadataY + 9, { width: 76, align: "center" });

      const clientText = [
        invoice.client.businessName,
        invoice.client.contactName,
        invoice.client.billingAddress,
        invoice.client.email,
        invoice.client.phone,
        invoice.client.taxId ? `Tax ID: ${invoice.client.taxId}` : undefined
      ]
        .filter(Boolean)
        .join("\n");
      const clientHeight = Math.max(
        82,
        document.heightOfString(clientText, { width: document.page.width - margin * 2 - 24 }) + 42
      );
      const clientY = 202;
      document.roundedRect(margin, clientY, document.page.width - margin * 2, clientHeight, 6).fill(colors.panel);
      document.fillColor(colors.brand).font("Helvetica-Bold").fontSize(8).text("BILL TO", margin + 12, clientY + 12);
      document
        .fillColor(colors.ink)
        .font("Helvetica")
        .fontSize(9)
        .text(clientText, margin + 12, clientY + 28, {
          width: document.page.width - margin * 2 - 24,
          lineGap: 2
        });

      let y = drawTableHeader(document, clientY + clientHeight + 24);
      for (const [index, item] of invoice.items.entries()) {
        const descriptionHeight = document.heightOfString(item.description, {
          width: tableColumns.description.width - 16,
          lineGap: 2
        });
        const rowHeight = Math.max(30, descriptionHeight + 14);
        y = ensureTableSpace(document, y, rowHeight);

        if (index % 2 === 1) document.rect(margin, y, 499, rowHeight).fill("#FAFBFD");
        document
          .fillColor(colors.ink)
          .font("Helvetica")
          .fontSize(9)
          .text(item.description, tableColumns.description.x + 8, y + 8, {
            width: tableColumns.description.width - 16,
            lineGap: 2
          })
          .text(item.quantity, tableColumns.quantity.x, y + 8, {
            width: tableColumns.quantity.width,
            align: "right"
          })
          .text(formatMoney(item.unitPrice, invoice.currency), tableColumns.unitPrice.x - 10, y + 8, {
            width: tableColumns.unitPrice.width + 10,
            align: "right"
          })
          .text(formatMoney(item.lineTotal, invoice.currency), tableColumns.lineTotal.x - 8, y + 8, {
            width: tableColumns.lineTotal.width,
            align: "right"
          });
        document.moveTo(margin, y + rowHeight).lineTo(document.page.width - margin, y + rowHeight).strokeColor(colors.line).stroke();
        y += rowHeight;
      }

      const notesText = invoice.notes ?? "No additional notes.";
      const notesHeight = document.heightOfString(notesText, { width: 255, lineGap: 2 });
      const summaryHeight = Math.max(118, notesHeight + 38);
      if (y + summaryHeight > document.page.height - 92) {
        document.addPage();
        y = margin;
      } else {
        y += 22;
      }

      document.fillColor(colors.muted).font("Helvetica-Bold").fontSize(8).text("NOTES", margin, y);
      document.fillColor(colors.ink).font("Helvetica").fontSize(9).text(notesText, margin, y + 16, {
        width: 255,
        lineGap: 2
      });

      const totalsX = 340;
      document.roundedRect(totalsX, y - 4, 207, 112, 6).fill(colors.panel);
      const totals = [
        ["Subtotal", formatMoney(invoice.subtotal, invoice.currency)],
        [`Tax (${invoice.taxRate}%)`, formatMoney(invoice.taxTotal, invoice.currency)]
      ];
      totals.forEach(([label, value], index) => {
        const rowY = y + 12 + index * 24;
        document.fillColor(colors.muted).font("Helvetica").fontSize(9).text(label!, totalsX + 12, rowY);
        document.fillColor(colors.ink).text(value!, totalsX + 82, rowY, { width: 113, align: "right" });
      });
      document.moveTo(totalsX + 12, y + 62).lineTo(totalsX + 195, y + 62).strokeColor(colors.line).stroke();
      document.fillColor(colors.ink).font("Helvetica-Bold").fontSize(10).text("TOTAL", totalsX + 12, y + 76);
      document
        .fillColor(colors.brand)
        .font("Helvetica-Bold")
        .fontSize(12)
        .text(formatMoney(invoice.grandTotal, invoice.currency), totalsX + 72, y + 74, {
          width: 123,
          align: "right"
        });

      drawFooter(document);
      document.end();
    });
  }
}
